// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PayTrack.Data;

#nullable disable

namespace PayTrack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526170000_AddDismissedDuplicatePaymentRequestByUser")]
    partial class AddDismissedDuplicatePaymentRequestByUser
    {
    }
}
