sonar.projectKey=PayTrack_Frontend
sonar.projectName=PayTrack_Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/api-types.ts,**/main.ts

sonar.typescript.tsconfigPath=tsconfig.json

sonar.javascript.lcov.reportPaths=coverage/**/lcov.info
