sonar.projectKey=PayTrack_Backend
sonar.projectName=PayTrack_Backend
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/bin/**,**/obj/**,**/Migrations/**,**/*.generated.cs,**/coverage-report/**

sonar.coverage.exclusions=**/Program.cs
