apiVersion: v1
kind: Secret
metadata:
  name: paytrack-secrets
  namespace: 26ss-ase-pr-qse-08
type: Opaque
stringData:
  POSTGRES_DB: "__SET_REAL_VALUE__"
  POSTGRES_USER: "__SET_REAL_VALUE__"
  POSTGRES_PASSWORD: "__SET_REAL_VALUE__"
  JWT__Secret: "__SET_REAL_VALUE__"
  GOOGLE_CLIENT_ID: "__SET_REAL_VALUE__"
  GOOGLE_CLIENT_SECRET: "__SET_REAL_VALUE__"
  PUSH_VAPID_PUBLIC_KEY: "__SET_REAL_VALUE__"
  PUSH_VAPID_PRIVATE_KEY: "__SET_REAL_VALUE__"
  PUSH_VAPID_SUBJECT: "__SET_REAL_VALUE__"
  ConnectionStrings__Default: "Host=paytrack-postgres;Port=5432;Database=__SET_REAL_VALUE__;Username=__SET_REAL_VALUE__;Password=__SET_REAL_VALUE__"
