/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GoogleAuthCallbackDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GoogleAuthResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/currentuser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bankaccount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BankAccountDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBankAccountRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BankAccountDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bankaccount/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBankAccountRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bankaccount/onboarding/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bankaccount/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBankAccountRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BankAccountDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cost-centre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Name?: string;
                    Description?: string;
                    MinBudget?: number;
                    MaxBudget?: number;
                    Limit?: number;
                    Offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CostCentreDtoPaginatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCostCentreRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CostCentreDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cost-centre/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CostCentreDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCostCentreRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CostCentreDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CostCentreDto"];
                    };
                };
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cost-centre/{id}/delete-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteCostCentrePreviewDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Name?: string;
                    Description?: string;
                    MinBudget?: number;
                    MaxBudget?: number;
                    IsActive?: boolean;
                    IncludeMembers?: boolean;
                    IncludeBudgets?: boolean;
                    Limit?: number;
                    Offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamDtoPaginatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTeamRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    IncludeMembers?: boolean;
                    IncludeBudgets?: boolean;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTeamRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamDto"];
                    };
                };
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/{id}/delete-impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteTeamImpactDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transaction/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    InvoiceNumber?: string;
                    PayoutType?: components["schemas"]["PayoutType"];
                    BankAccountId?: number;
                    IncludeBankAccount?: boolean;
                    UserId?: number;
                    MinAmount?: number;
                    MaxAmount?: number;
                    PurposeOfPayment?: string;
                    PaymentReference?: string;
                    Status?: components["schemas"]["TransactionStatus"];
                    CostCentreId?: number;
                    TeamId?: number;
                    PaymentDirection?: components["schemas"]["PaymentDirection"];
                    MinCreatedAt?: string;
                    MaxCreatedAt?: string;
                    MinPaidAt?: string;
                    MaxPaidAt?: string;
                    Limit?: number;
                    Offset?: number;
                    IncludeCostCentre?: boolean;
                    IncludeTeam?: boolean;
                    IncludeStatusHistory?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentRequestByUserDtoPaginatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": components["schemas"]["CreatePaymentRequestByUserDto"];
                    "application/x-www-form-urlencoded": components["schemas"]["CreatePaymentRequestByUserDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentRequestByUserDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transaction/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    IncludeBankAccount?: boolean;
                    IncludeCostCentre?: boolean;
                    IncludeUser?: boolean;
                    IncludeTeam?: boolean;
                    IncludeStatusHistory?: boolean;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentRequestByUserDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePaymentRequestByUserDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentRequestByUserDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transaction/user/{id}/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transaction/user/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    TeamId: number;
                    Amount: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DuplicatePaymentRequestByUserDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Name?: string;
                    Email?: string;
                    TeamName?: string;
                    Role?: components["schemas"]["Role"];
                    IsActive?: boolean;
                    IncludeTeam?: boolean;
                    Limit?: number;
                    Offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDtoPaginatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    IncludeTeam?: boolean;
                    IncludeBankAccounts?: boolean;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BankAccountDto: {
            /** Format: int32 */
            id: number;
            accountHolder: string;
            iban: string;
            bic: string;
        };
        BudgetDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            teamId: number;
            /** Format: int32 */
            costCentreId: number;
            /** Format: double */
            targetAmount: number;
            /** Format: date-time */
            periodStart: string;
            /** Format: date-time */
            periodEnd: string;
        };
        CostCentreDto: {
            /** Format: int32 */
            id: number;
            name: string;
            description?: string | null;
            displayColor?: string | null;
            budgets?: components["schemas"]["BudgetDto"][] | null;
            isActive?: boolean;
        };
        CostCentreDtoPaginatedResponse: {
            items: components["schemas"]["CostCentreDto"][] | null;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            offset: number;
            readonly hasNext?: boolean;
            readonly hasPrevious?: boolean;
        };
        CreateBankAccountRequestDto: {
            accountHolder: string;
            iban: string;
            bic: string;
        };
        CreateCostCentreBudgetEntryDto: {
            /** Format: int32 */
            teamId: number;
            /** Format: double */
            targetAmount: number;
            /** Format: date-time */
            periodStart: string;
            /** Format: date-time */
            periodEnd: string;
        };
        CreateCostCentreRequestDto: {
            name: string;
            description?: string | null;
            displayColor?: string | null;
            budgets?: components["schemas"]["CreateCostCentreBudgetEntryDto"][] | null;
        };
        CreatePaymentRequestByUserDto: {
            transaction: components["schemas"]["CreateTransactionDto"];
            invoiceNumber: string;
            comment?: string | null;
            /** Format: binary */
            receipt: string;
            payoutType: components["schemas"]["PayoutType"];
            /** Format: int32 */
            bankAccountId: number;
        };
        CreateTeamBudgetEntryDto: {
            /** Format: int32 */
            costCentreId: number;
            /** Format: double */
            targetAmount: number;
            /** Format: date-time */
            periodStart: string;
            /** Format: date-time */
            periodEnd: string;
        };
        CreateTeamRequestDto: {
            name: string;
            description?: string | null;
            displayColor?: string | null;
            budgets?: components["schemas"]["CreateTeamBudgetEntryDto"][] | null;
        };
        CreateTransactionDto: {
            /** Format: int32 */
            teamId: number;
            /** Format: double */
            amount: number;
            purposeOfPayment: string;
            /** Format: date-time */
            paidAt: string;
        };
        DeleteCostCentrePreviewDto: {
            costCentreName: string;
            /** Format: int32 */
            budgetCount: number;
            /** Format: int32 */
            transactionCount: number;
            /** Format: int32 */
            affectedUserCount: number;
            affectedTeamNames: string[];
        };
        DeleteTeamImpactDto: {
            /** Format: int32 */
            teamId?: number;
            teamName?: string | null;
            canDelete?: boolean;
            /** Format: int32 */
            affectedUserCount?: number;
            /** Format: int32 */
            blockingBudgetCount?: number;
            /** Format: int32 */
            blockingTransactionCount?: number;
            /** Format: int32 */
            invoiceCount?: number;
            warningMessage?: string | null;
        };
        DuplicatePaymentRequestByUserDto: {
            paymentRequestByUser: components["schemas"]["PaymentRequestByUserDto"];
            /** Format: int32 */
            score: number;
            isAmountAndUserMatch: boolean;
            isAmountAndTeamMatch: boolean;
        };
        GoogleAuthCallbackDto: {
            code: string;
        };
        GoogleAuthResponseDto: {
            jwtToken: string;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        PaymentDirection: 0 | 1;
        PaymentRequestByUserDto: {
            /** Format: int32 */
            id: number;
            user?: components["schemas"]["UserDto"];
            /** Format: double */
            amount: number;
            purposeOfPayment?: string | null;
            paymentReference?: string | null;
            status: components["schemas"]["TransactionStatus"];
            costCentre?: components["schemas"]["CostCentreDto"];
            team?: components["schemas"]["TeamDto"];
            paymentDirection?: components["schemas"]["PaymentDirection"];
            statusHistory?: components["schemas"]["TransactionStatusHistoryDto"][] | null;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            paidAt?: string | null;
            invoiceNumber: string;
            comment?: string | null;
            payoutType: components["schemas"]["PayoutType"];
            bankAccount?: components["schemas"]["BankAccountDto"];
        };
        PaymentRequestByUserDtoPaginatedResponse: {
            items: components["schemas"]["PaymentRequestByUserDto"][] | null;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            offset: number;
            readonly hasNext?: boolean;
            readonly hasPrevious?: boolean;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        PayoutType: 0 | 1;
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        Role: 0 | 1 | 2;
        TeamDto: {
            /** Format: int32 */
            id: number;
            name: string;
            description?: string | null;
            displayColor?: string | null;
            members?: components["schemas"]["UserDto"][] | null;
            budgets?: components["schemas"]["BudgetDto"][] | null;
            isActive?: boolean;
        };
        TeamDtoPaginatedResponse: {
            items: components["schemas"]["TeamDto"][] | null;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            offset: number;
            readonly hasNext?: boolean;
            readonly hasPrevious?: boolean;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        TransactionStatus: 0 | 1 | 2 | 3 | 4;
        TransactionStatusHistoryDto: {
            /** Format: int32 */
            changedById: number;
            comment: string;
            fromStatus: components["schemas"]["TransactionStatus"];
            toStatus: components["schemas"]["TransactionStatus"];
            /** Format: date-time */
            changedAt: string;
        };
        UpdateBankAccountRequestDto: {
            accountHolder?: string | null;
            iban?: string | null;
            bic?: string | null;
        };
        UpdateCostCentreRequestDto: {
            name?: string | null;
            description?: string | null;
            displayColor?: string | null;
            budgetsToUpsert?: components["schemas"]["UpsertCostCentreBudgetEntryDto"][] | null;
            budgetIdsToDelete?: number[] | null;
        };
        UpdatePaymentRequestByUserDto: {
            transaction: components["schemas"]["UpdateTransactionDto"];
            invoiceNumber?: string | null;
            comment?: string | null;
            payoutType?: components["schemas"]["PayoutType"];
            /** Format: int32 */
            bankAccountId?: number | null;
        };
        UpdateTeamRequestDto: {
            name?: string | null;
            description?: string | null;
            displayColor?: string | null;
            budgetsToUpsert?: components["schemas"]["UpsertTeamBudgetEntryDto"][] | null;
            budgetIdsToDelete?: number[] | null;
        };
        UpdateTransactionDto: {
            /** Format: int32 */
            teamId?: number | null;
            /** Format: double */
            amount?: number | null;
            purposeOfPayment?: string | null;
            /** Format: date-time */
            paidAt?: string | null;
        };
        UpdateUserDto: {
            name?: string | null;
            role?: components["schemas"]["Role"];
            isActive?: boolean | null;
            /** Format: int32 */
            teamId?: number | null;
        };
        UpsertCostCentreBudgetEntryDto: {
            /** Format: int32 */
            id?: number | null;
            /** Format: int32 */
            teamId: number;
            /** Format: double */
            targetAmount: number;
            /** Format: date-time */
            periodStart: string;
            /** Format: date-time */
            periodEnd: string;
        };
        UpsertTeamBudgetEntryDto: {
            /** Format: int32 */
            id?: number | null;
            /** Format: int32 */
            costCentreId: number;
            /** Format: double */
            targetAmount: number;
            /** Format: date-time */
            periodStart: string;
            /** Format: date-time */
            periodEnd: string;
        };
        UserDto: {
            /** Format: int32 */
            id: number;
            name: string;
            email: string;
            profilePictureUrl: string;
            role: components["schemas"]["Role"];
            isActive: boolean;
            team: components["schemas"]["TeamDto"];
            bankInformationSkipped: boolean;
            hasBankInformation: boolean;
            bankAccounts?: components["schemas"]["BankAccountDto"][] | null;
        };
        UserDtoPaginatedResponse: {
            items: components["schemas"]["UserDto"][] | null;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            offset: number;
            readonly hasNext?: boolean;
            readonly hasPrevious?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
